# -*- coding: utf-8 -*-
"""Laba 6 zadanie 6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y0RJpCRvbZ8GvisDm0NgmTbiX4s2_gy4
"""

import numpy as np
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt


fashion_mnist = keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

train_images = train_images / 255.0
test_images = test_images / 255.0
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(train_images, train_labels, epochs=5)
predictions = model.predict(test_images)

for i in range(5):
    plt.imshow(test_images[i], cmap='gray')
    plt.title(f'Предсказание: {np.argmax(predictions[i])}')
    plt.show()